export const metadata = {
  title: "My Services || Care.io",
  description: "Generated by create next app",
};

const MyServices = () => {
  return <div>MyServices MyServices</div>;
};

export default MyServices;
