import RegisterForm from "./RegisterForm";

export const metadata = {
  title: "Register || Care.io",
  description: "Generated by create next app",
};

const Register = () => {
  return <RegisterForm></RegisterForm>;
};

export default Register;
