import MyBookingsProvider from "./MyBookingsProvider";

export const metadata = {
  title: "My Bookings || Care.io",
  description: "Generated by create next app",
};

const MyBookings = () => {
  return <MyBookingsProvider></MyBookingsProvider>;
};

export default MyBookings;
