import ProfileProvider from "./ProfileProvider";

export const metadata = {
  title: "Profile || Care.io",
  description: "Generated by create next app",
};

const Profile = () => {
  return <ProfileProvider></ProfileProvider>;
};

export default Profile;
