import ServicesPage from "./ServicesPage";

export const metadata = {
  title: "Services || Care.io",
  description: "Generated by create next app",
};

const Services = () => {
  return <ServicesPage></ServicesPage>;
};

export default Services;
