import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Providers from "@/components/providers/Providers";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Care.io - Best Care",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col items-center bg-[#030712] text-slate-200 min-h-screen`}
      >
        <Providers>
          <Navbar></Navbar>
          <div className="py-8"></div>
          {children}
          <Footer></Footer>
        </Providers>
        <ToastContainer></ToastContainer>
      </body>
    </html>
  );
}
