import ServiceDetails from "./ServiceDetails";

export const metadata = {
  title: "Service Details || Care.io",
  description: "Generated by create next app",
};

const Service = () => {
  return <ServiceDetails></ServiceDetails>;
};

export default Service;
